services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Rio Ferdinan"
        STUDENT_NIM: "00000070666"
    ports:
      - "80:80"
    command: ["pnpm", "run", "dev", "--", "--port", "80", "--host", "0.0.0.0"]
